# Generated by Django 3.0.2 on 2020-03-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0025_auto_20200301_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassador',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_currency',
            field=models.IntegerField(choices=[(1, 'UZS'), (2, 'USD')], verbose_name='Payment currency'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='paysystransaction',
            name='payment_environment',
            field=models.IntegerField(choices=[(1, 'LIVE'), (2, 'SANDBOX')], default=1, verbose_name='EVIRONMENT'),
        ),
        migrations.AlterField(
            model_name='paysystransaction',
            name='payment_vendor_trans_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date'),
        ),
    ]
