# Generated by Django 3.0.2 on 2020-03-10 16:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200310_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassyTransaction',
            fields=[
                ('raw_total_gross_amount', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='raw_total_gross_amount')),
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='id')),
                ('status', models.CharField(choices=[('success', 'SUCCESS'), ('incomplete', 'INCOMPLETE'), ('canceled', 'CANCELED'), ('refunded', 'REFUNDED'), ('cb_initiated', 'CB_INITIATED'), ('cb_lost', 'CB_LOST'), ('test', 'TEST')], default='cb_initiated', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created_at')),
                ('member_name', models.CharField(max_length=50, verbose_name='member_name')),
                ('member_email_address', models.EmailField(max_length=80, verbose_name='member_email_address')),
                ('member_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='member_phone')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='comment')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='is_anonymous')),
                ('is_gift_aid', models.BooleanField(default=False, verbose_name='is_gift_aid')),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Donation')),
            ],
            options={
                'verbose_name': 'CLASSY Transaction',
                'verbose_name_plural': 'CLASSY Transactions',
            },
        ),
    ]
