# Generated by Django 3.0.2 on 2020-03-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200310_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classytransaction',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='classytransaction',
            name='member_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='member_phone'),
        ),
        migrations.AlterField(
            model_name='classytransaction',
            name='raw_total_gross_amount',
            field=models.FloatField(db_index=True, verbose_name='raw_total_gross_amount'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(db_index=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='paysystransaction',
            name='payment_merchant_trans_amount',
            field=models.IntegerField(db_index=True, verbose_name='MERCHANT_TRANS_AMOUNT'),
        ),
        migrations.AlterField(
            model_name='paysystransaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone number'),
        ),
    ]
