# Generated by Django 3.0.2 on 2024-04-08 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Is Published')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'News Entry',
                'verbose_name_plural': 'News Entries',
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
