# Generated by Django 3.0.2 on 2024-04-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240408_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Title'),
        ),
    ]
