# Generated by Django 3.0.2 on 2025-05-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20240408_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Uzbek)'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Title (Russian)'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Title (Uzbek)'),
        ),
    ]
